import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { cookieToInitialState } from "wagmi";
import { headers } from "next/headers";
import WalletConnectProvider from "@/providers/WalletConnectProvider";
import { wagmiConfig } from "@/config/wagmiConfig";
import { ComposeClientContextProvider } from "@/providers/ComposeClientContextProvider";
import { AuthSessionProvider } from "@/providers/AuthSessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(
    wagmiConfig,
    headers().get("cookie")
  );

  return (
    <html lang="en" data-theme="retro">
      <body className={inter.className}>
        <WalletConnectProvider initialState={initialState}>
          <ComposeClientContextProvider>
            <AuthSessionProvider>
              <Navbar />
              {children}
            </AuthSessionProvider>
          </ComposeClientContextProvider>
        </WalletConnectProvider>
      </body>
    </html>
  );
}
